spring:
  application:
    name: vehicle-service
  data:
    mongodb:
      uri: mongodb://admin:senha123@ds141208.mlab.com:41208/springclouddb
      #host: ${MONGO_HOST:cluster0-1h4ej.mongodb.net}
      #port: ${MONGO_PORT:27018}
      database: springclouddb
server:
  port: 8083
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream
br:
  com:
    danilopaixao:
      service:
        driver:
          protocol: http 
          host: driver-service
          version: v1 
        vehicle:
          socket:
            url: ${WEB_SOCKET_PROTOCOL:http}://${WEB_SOCKET_HOST:vehicle-websocket}:${WEB_SOCKET_PORT:8085}