spring:
  application:
    name: vehicle-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27018}
      database: ${MONGO_DATABASE:vehicledb}
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream
br:
  com:
    danilopaixao:
      service:
        driver:
          protocol: http 
          host: driver-service
          version: v1 
        vehicle:
          socket:
            url: ${WEB_SOCKET_PROTOCOL:http}://${WEB_SOCKET_HOST:vehicle-websocket}:${WEB_SOCKET_PORT:8085}