spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write-dates-as-timestamps: false
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: vehicle-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:senha123@ds141208.mlab.com:41208/springclouddb}
      database: ${MONGODB_DATABASE:springclouddb}
  rabbitmq:
    addresses: ${RABBIT_MQ_ADDRESS:chimpanzee.rmq.cloudamqp.com/zcdpcvpk}
    port: ${RABBIT_MQ_PORT:5672} 
    username: ${RABBIT_MQ_USER:zcdpcvpk}
    password: ${RABBIT_MQ_PASSWORD:jYbSUveUBNCCYhXqYQg9OXDuLqaZe4Kr}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 6
server:
  port: ${SERVER_PORT:8080}
eureka:
  client:
    enabled: ${ENABLED_EUREKA:false}
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream
queue:
  vehicle: VehicleQueue
br:
  com:
    danilopaixao:
      service:
        driver:
          url: ${DRIVER_SERVICE_URL:http://localhost:8082/api/v1}
        vehicle:
          socket:
            url: ${WEB_SOCKET_SERVER_URL:http://localhost:8085/api/v1/vehicle}